name: Bug Report
description: Submit a bug report. If you're having an issue that tech support could fix, create a discussion or join our discord server instead.
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      ## Bug Report
- type: dropdown
  attributes:
    label: MacOS version
    description: Select all applicable versions
    multiple: true
    options:
    - macOS 11 (Big Sur)
    - macOS 12 (Monterey)
    - macOS 13 (Ventura)
- type: textarea
  attributes:
    label: Version of InnateMC
    description: The version of InnateMC being used. Find out in InnateMC > About InnateMC
    placeholder: 0.1.0
  validations:
    required: true
- type: textarea
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: A bug happened!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A description on how this bug can be reproduced
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
