name: Feature Request
description: Make a feature request or suggestion. For large proposed changes and RFCs, please create a discussion instead.
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ## Feature Request
- type: input
  attributes:
    label: Feature Request
    description: What feature do you want?
    placeholder: PearOS version
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
